import fs from "fs";
import Link from "next/link";
import { env } from "@/lib/env";

function readHederaEvidence() {
  try { return JSON.parse(fs.readFileSync(env.hederaEvidencePath, "utf8")) as { bondAddress: string; bondHashscan: string; asset: { name: string; symbol: string } }; } catch { return null; }
}

function Chip({ children }: { children: React.ReactNode }) { return <span className="mono text-[10px] uppercase tracking-[0.14em] border border-line px-2.5 py-1.5 text-paper/55 rounded-sm">{children}</span>; }

function ProductPanel() {
  return <div className="border border-line bg-[#0d0d0d] shadow-2xl shadow-black/30"><div className="flex items-center justify-between border-b border-line/70 px-4 py-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-safe" /><span className="mono text-[10px] uppercase tracking-[0.16em] text-paper/45">Live account view</span></div><span className="mono text-[10px] text-paper/25">ACCOUNT / 0x4A30…0602</span></div><div className="grid md:grid-cols-[1.05fr_0.95fr] divide-y md:divide-y-0 md:divide-x divide-line/70"><div className="p-5 md:p-7"><div className="flex items-center justify-between mb-7"><div><p className="mono text-[10px] uppercase tracking-[0.14em] text-paper/35">Account posture</p><p className="text-lg font-medium mt-1">Stable across domains</p></div><span className="mono text-xs text-safe border border-safe/30 bg-safe/10 px-2 py-1">HEALTHY</span></div><div className="grid grid-cols-2 gap-5"><div><p className="text-xs text-paper/35">Health factor</p><p className="mono text-3xl mt-1">1.62</p><p className="text-xs text-safe mt-1">Within policy</p></div><div><p className="text-xs text-paper/35">Protected balance</p><p className="mono text-3xl mt-1">1,000</p><p className="text-xs text-paper/35 mt-1">FWM-NOTE · Hedera</p></div></div><div className="mt-8 border-t border-line/70 pt-4 flex items-center justify-between"><span className="text-xs text-paper/35">Next policy evaluation</span><span className="mono text-xs text-paper/60">in 00:58</span></div></div><div className="p-5 md:p-7"><div className="flex items-center gap-2 mb-5"><span className="h-1.5 w-1.5 rounded-full bg-signal" /><p className="mono text-[10px] uppercase tracking-[0.14em] text-paper/40">Confidential decision path</p></div><div className="space-y-4"><div className="flex gap-3"><span className="mono text-[10px] text-paper/30 pt-0.5">01</span><div><p className="text-sm">Live market exposure</p><p className="text-xs text-paper/35 mt-1">The Graph · 4 standardized markets</p></div></div><div className="h-px bg-line/70 ml-6" /><div className="flex gap-3"><span className="mono text-[10px] text-paper/30 pt-0.5">02</span><div><p className="text-sm">Private policy evaluation</p><p className="text-xs text-paper/35 mt-1">Chainlink CRE · Nitro TEE</p></div></div><div className="h-px bg-line/70 ml-6" /><div className="flex gap-3"><span className="mono text-[10px] text-paper/30 pt-0.5">03</span><div><p className="text-sm">Selective action</p><p className="text-xs text-paper/35 mt-1">Sepolia only · Hedera unreachable</p></div></div></div><div className="mt-7 border border-safe/20 bg-safe/[0.04] p-3 flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-safe" /><span className="text-xs text-paper/60">No active protection events</span></div></div></div></div>;
}

function Capability({ number, title, body, label }: { number: string; title: string; body: string; label: string }) { return <div className="border-t border-line/70 pt-5 flex flex-col gap-3"><div className="flex justify-between"><span className="mono text-[10px] text-paper/25">{number}</span><span className="mono text-[10px] uppercase tracking-widest text-paper/35">{label}</span></div><h3 className="text-lg font-medium tracking-tight">{title}</h3><p className="text-sm text-paper/45 leading-relaxed">{body}</p></div>; }

export default function Landing() {
  const hedera = readHederaEvidence();
  return <main className="min-h-screen overflow-hidden"><nav className="max-w-7xl mx-auto px-6 lg:px-10 py-6 flex items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="h-3 w-3 bg-signal rounded-sm" /><span className="mono text-xs uppercase tracking-[0.22em] text-paper/75">Galvanic</span></Link><div className="hidden md:flex items-center gap-7 text-sm text-paper/45"><a href="#product" className="hover:text-paper">Product</a><a href="#how-it-works" className="hover:text-paper">How it works</a><a href="#infrastructure" className="hover:text-paper">Infrastructure</a></div><Link href="/dashboard" className="mono text-[11px] uppercase tracking-wide border border-signal text-signal rounded-sm px-4 py-2.5 hover:bg-signal/10">Open dashboard →</Link></nav>

    <section className="max-w-7xl mx-auto px-6 lg:px-10 pt-20 md:pt-28 pb-20"><div className="grid lg:grid-cols-[0.9fr_1.1fr] gap-14 xl:gap-24 items-center"><div className="flex flex-col items-start gap-7"><div className="flex items-center gap-3"><span className="h-1.5 w-1.5 bg-signal rounded-full pulse" /><span className="mono text-[10px] uppercase tracking-[0.18em] text-paper/40">Isolated collateral. Confidential decisions.</span></div><h1 className="text-5xl md:text-7xl font-semibold tracking-[-0.05em] leading-[0.94] max-w-2xl">Know what can move before anything moves.</h1><p className="text-base md:text-lg text-paper/50 leading-relaxed max-w-xl">Galvanic gives risk teams a live operating view of volatile and protected collateral—then evaluates liquidation policy privately, before a single action crosses a custody boundary.</p><div className="flex flex-wrap gap-3"><Link href="/dashboard" className="mono text-xs uppercase tracking-wide border border-signal bg-signal/10 text-signal rounded-sm px-5 py-3 hover:bg-signal/20">Open dashboard →</Link><a href="#how-it-works" className="mono text-xs uppercase tracking-wide border border-line text-paper/60 rounded-sm px-5 py-3 hover:bg-white/5">See the operating model</a></div><div className="flex flex-wrap gap-2 pt-1"><Chip>Hedera ATS</Chip><Chip>The Graph</Chip><Chip>Chainlink CRE</Chip></div></div><div id="product"><ProductPanel /></div></div></section>

    <section className="border-y border-line/60 bg-white/[0.02]"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-5 flex flex-col md:flex-row md:items-center gap-4 md:gap-12"><span className="mono text-[10px] uppercase tracking-[0.16em] text-paper/30">Built for real operations</span><div className="flex flex-wrap gap-x-8 gap-y-2 text-sm text-paper/50"><span><i className="inline-block h-1.5 w-1.5 rounded-full bg-safe mr-2" />Protected assets stay protected</span><span><i className="inline-block h-1.5 w-1.5 rounded-full bg-signal mr-2" />Liquid risk stays actionable</span><span><i className="inline-block h-1.5 w-1.5 rounded-full bg-paper/30 mr-2" />Policy stays private</span></div></div></section>

    <section id="how-it-works" className="max-w-7xl mx-auto px-6 lg:px-10 py-24"><div className="max-w-2xl mb-14"><span className="mono text-[10px] uppercase tracking-[0.18em] text-signal/80">The operating model</span><h2 className="text-3xl md:text-5xl font-semibold tracking-tight mt-4">A risk workflow designed around boundaries.</h2><p className="text-paper/45 leading-relaxed mt-5">Most collateral systems make isolation a policy choice inside one pool. Galvanic makes the boundary visible, auditable, and structural.</p></div><div className="grid md:grid-cols-3 gap-10"><Capability number="01" label="Observe" title="See the whole exposure picture" body="A single account view joins the Sepolia liquid position with live, standardized lending data across external protocols." /><Capability number="02" label="Evaluate" title="Keep policy out of the public path" body="Private thresholds and raw risk inputs are evaluated inside a Chainlink CRE confidential workflow. The operating team sees the decision, not the secrets." /><Capability number="03" label="Act" title="Move only what is allowed to move" body="A signed decision can act on the liquid crypto leg. The Hedera asset has no bridge or contract path into the liquidation flow." /></div></section>

    <section id="infrastructure" className="max-w-7xl mx-auto px-6 lg:px-10 pb-24"><div className="border border-line"><div className="p-6 md:p-8 border-b border-line/70 flex flex-col md:flex-row md:items-end justify-between gap-5"><div><span className="mono text-[10px] uppercase tracking-[0.18em] text-paper/35">Infrastructure</span><h2 className="text-2xl md:text-3xl font-semibold tracking-tight mt-3">One operating view. Separate custody domains.</h2></div><span className="mono text-[10px] text-paper/35">TESTNET ENVIRONMENT / LIVE EVIDENCE</span></div><div className="grid md:grid-cols-3 divide-y md:divide-y-0 md:divide-x divide-line/70"><div className="p-6 md:p-8"><span className="mono text-[10px] uppercase tracking-widest text-safe">Protected domain</span><h3 className="text-lg font-medium mt-3">Hedera ATS</h3><p className="text-sm text-paper/40 leading-relaxed mt-3">A real KYC-gated security token with compliant transfer lifecycle. {hedera ? <a href={hedera.bondHashscan} target="_blank" rel="noreferrer" className="text-safe underline underline-offset-4">View evidence</a> : "Evidence pending."}</p></div><div className="p-6 md:p-8"><span className="mono text-[10px] uppercase tracking-widest text-paper/50">Network intelligence</span><h3 className="text-lg font-medium mt-3">The Graph</h3><p className="text-sm text-paper/40 leading-relaxed mt-3">A standardized Lending schema reused across real protocol deployments, giving the account a common exposure language.</p></div><div className="p-6 md:p-8"><span className="mono text-[10px] uppercase tracking-widest text-signal">Private policy</span><h3 className="text-lg font-medium mt-3">Chainlink CRE</h3><p className="text-sm text-paper/40 leading-relaxed mt-3">A confidential workflow turns private thresholds and live inputs into one auditable, selective action.</p></div></div></div></section>

    <section className="border-t border-line/60"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-24 flex flex-col md:flex-row md:items-end justify-between gap-8"><div><span className="mono text-[10px] uppercase tracking-[0.18em] text-paper/35">For risk operators</span><h2 className="text-3xl md:text-5xl font-semibold tracking-tight mt-4 max-w-2xl">Turn a dangerous event into a contained one.</h2></div><Link href="/dashboard" className="mono text-xs uppercase tracking-wide border border-signal bg-signal/10 text-signal rounded-sm px-5 py-3 shrink-0 hover:bg-signal/20">Open dashboard →</Link></div></section>
    <footer className="max-w-7xl mx-auto px-6 lg:px-10 py-7 border-t border-line/60 flex justify-between gap-4 text-[10px] mono uppercase tracking-widest text-paper/25"><span>Galvanic / Isolated collateral. Confidential decisions.</span><span>Hedera · The Graph · Chainlink</span></footer>
  </main>;
}
